version: '3.7'
services:

    # The Application
    app:
        build: .
        container_name: webapp
        working_dir: /webapp
        volumes:
            - ./webapp/:/webapp
        #command: bash -c "cd /webapp && composer install"

    web:
        image: nginx:1.8
        container_name: webserver
        ports:
            - '8000:80'
        depends_on:
            - app
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - .:/webapp
            
    #The database
    database:
        image: mysql:5.7
        container_name: mysql
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_USER=trungnn"
            - "MYSQL_PASSWORD=123456"
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE_1=my_system"
        ports:
            - "3307:3306"
    
volumes:
    dbdata: